#!/bin/sh

SPEEDS="32 35 40"



doit() {
  echo "FILE: $2 NAME: $3 SPEED: $1 TRACKNUM $4"
  rm -f ./tmp$1.wav
  #../../cwwav -O wav -e 18 -f 660 -w $1 -o ./tmp$1.wav $2
  # Above 30WPM, e=18 is too high
  ../../cwwav -O wav -e 15 -f 660 -w $1 -o ./tmp$1.wav $2
  mkdir -p o/$1
  lame --preset cbr 16 --tn "$4" --tt "$3" --ta "Mark Twain" --tl "Huckleberry Finn $1 WPM" ./tmp$1.wav "o/$1/$3.mp3"
}

n=1
for b in [0-9]*; do
  for a in $SPEEDS; do
    doit $a $b "Chapter $b" $n &
  done
  n=$((n + 1))
  wait
done
